language: php

node_js:
    - "6"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6

before_script:
  - cd .src && npm install -g grunt-cli
  - npm install
  - composer install
  - npm prune
  - npm --version
  - node --version

script:
  - grunt phpcs
